"use client"
 
import Link from "next/link"
import { motion } from "framer-motion"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import AIChatButton from "@/components/ai-chat-button"
 
const sections = [
  {
    number: "01",
    title: "Acceptance of Terms",
    content: "By accessing and using HY MBAGRAD, you accept and agree to be bound by these Terms and Conditions. If you do not agree, please do not use our platform."
  },
  {
    number: "02",
    title: "Use of Platform",
    content: "HY MBAGRAD is a free educational platform for CAT exam preparation. You must be 18 years or older to use this platform. You agree not to misuse, copy, or redistribute our content. You agree not to use automated tools to scrape our platform."
  },
  {
    number: "03",
    title: "AI Assistant Usage",
    content: "Our CAT AI assistant is provided for educational guidance only. Responses generated by the AI are not guaranteed to be 100% accurate. Always verify important information from official CAT sources. HY MBAGRAD is not responsible for decisions made based on AI responses."
  },
  {
    number: "04",
    title: "Free Resources",
    content: "All resources including mock tests, PYQs, and NCERT materials are provided for personal educational use only. Redistribution or commercial use of these resources is strictly prohibited."
  },
  {
    number: "05",
    title: "Intellectual Property",
    content: "All content on HY MBAGRAD including text, design, and AI-generated content is the property of HY MBAGRAD. Unauthorized reproduction is prohibited."
  },
  {
    number: "06",
    title: "Third Party Links",
    content: "Our platform contains links to external platforms such as YouTube, Telegram, and Discord. We are not responsible for content or practices of these external platforms."
  },
  {
    number: "07",
    title: "Disclaimer of Warranties",
    content: "HY MBAGRAD is provided on an 'as is' basis. We do not guarantee uninterrupted access or that the platform will be error-free. Mock test scores and AI guidance are for practice purposes only and do not guarantee performance in the actual CAT examination."
  },
  {
    number: "08",
    title: "Limitation of Liability",
    content: "HY MBAGRAD shall not be liable for any indirect or consequential damages arising from your use of the platform."
  },
  {
    number: "09",
    title: "Changes to Terms",
    content: "We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms."
  },
  {
    number: "10",
    title: "Contact",
    content: null
  }
]
 
export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0F172A]">
      <Navbar />
 
      {/* Hero */}
      <section className="pt-32 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
            className="text-[#F59E0B] text-sm font-semibold uppercase tracking-widest mb-4"
          >
            Legal
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-4xl sm:text-5xl font-bold text-white mb-4 tracking-tight"
          >
            Terms & Conditions
          </motion.h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-gray-500 text-sm"
          >
            Last updated: April 2026
          </motion.p>
        </div>
      </section>
 
      {/* Sections */}
      <section className="pb-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto space-y-0">
          {sections.map((section, index) => (
            <motion.div
              key={section.number}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.05 }}
              viewport={{ once: true }}
              className="border-t border-white/[0.06] py-10"
            >
              <div className="flex gap-8">
                <span className="text-[#F59E0B] text-sm font-mono font-semibold flex-shrink-0 mt-1">
                  {section.number}
                </span>
                <div>
                  <h2 className="text-lg font-semibold text-white mb-4">
                    {section.title}
                  </h2>
                  {section.content ? (
                    <p className="text-gray-400 leading-relaxed text-[15px]">
                      {section.content}
                    </p>
                  ) : (
                    <p className="text-gray-400 leading-relaxed text-[15px]">
                      For any questions regarding these Terms, reach us through our{" "}
                      <Link
                        href="https://t.me/hymbagrad"
                        target="_blank"
                        className="text-[#F59E0B] hover:text-amber-400 transition-colors"
                      >
                        Telegram channel
                      </Link>{" "}
                      or{" "}
                      <Link
                        href="https://discord.gg/hymbagrad"
                        target="_blank"
                        className="text-[#F59E0B] hover:text-amber-400 transition-colors"
                      >
                        Discord server
                      </Link>
                      .
                    </p>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
 
          {/* Back to home */}
          <div className="border-t border-white/[0.06] pt-10">
            <Link
              href="/"
              className="text-sm text-gray-500 hover:text-white transition-colors duration-200"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </section>
 
      <Footer />
      <AIChatButton />
    </main>
  )
}
 